// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSNumber;
@class NSDictionary;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Address")
@interface Address : NSObject
@property (nonatomic, copy) NSString * __nullable streetName;
@property (nonatomic, strong) NSNumber * __nullable streetNumber;
@property (nonatomic, copy) NSString * __nullable zipCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithStreetName:(NSString * __nullable)streetName streetNumber:(NSNumber * __nullable)streetNumber zipCode:(NSString * __nullable)zipCode OBJC_DESIGNATED_INITIALIZER;
+ (Address * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end

@class Cause;

SWIFT_CLASS("_TtC14MercadoPagoSDK12ApiException")
@interface ApiException : NSObject
@property (nonatomic, strong) Cause * __null_unspecified cause;
@property (nonatomic, copy) NSString * __null_unspecified error;
@property (nonatomic, copy) NSString * __null_unspecified message;
@property (nonatomic) NSInteger status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;

SWIFT_CLASS("_TtC14MercadoPagoSDK12Serializable")
@interface Serializable : NSObject

/// Converts the class to a dictionary.
///
/// \returns  The class as an NSDictionary.
- (NSDictionary * __nonnull)toDictionary;

/// Converts the class to JSON.
///
/// \returns  The class as JSON, wrapped in NSData.
- (NSData * __nullable)toJson:(BOOL)prettyPrinted;

/// Converts the class to a JSON string.
///
/// \returns  The class as a JSON string.
- (NSString * __nullable)toJsonString:(BOOL)prettyPrinted;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK3Bin")
@interface Bin : Serializable
@property (nonatomic, copy) NSString * __null_unspecified exclusionPattern;
@property (nonatomic, copy) NSString * __null_unspecified installmentsPattern;
@property (nonatomic, copy) NSString * __null_unspecified pattern;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Bin * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end

@class Cardholder;
@class NSDate;
@class PaymentMethod;
@class Issuer;
@class SecurityCode;

SWIFT_CLASS("_TtC14MercadoPagoSDK4Card")
@interface Card : NSObject
@property (nonatomic, strong) Cardholder * __nullable cardHolder;
@property (nonatomic, copy) NSString * __nullable customerId;
@property (nonatomic, strong) NSDate * __nullable dateCreated;
@property (nonatomic, strong) NSDate * __nullable dateLastUpdated;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, copy) NSString * __nullable firstSixDigits;
@property (nonatomic, strong) NSNumber * __nonnull idCard;
@property (nonatomic, copy) NSString * __nullable lastFourDigits;
@property (nonatomic, strong) PaymentMethod * __nullable paymentMethod;
@property (nonatomic, strong) Issuer * __nullable issuer;
@property (nonatomic, strong) SecurityCode * __nullable securityCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Card * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (BOOL)isSecurityCodeRequired;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardIssuer")
@interface CardIssuer : NSObject
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic, copy) NSString * __null_unspecified name;
@property (nonatomic, copy) NSArray<NSString *> * __null_unspecified labels;
- (nonnull instancetype)initWith_id:(NSString * __nonnull)_id name:(NSString * __nullable)name labels:(NSArray<NSString *> * __nonnull)labels OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardNumber")
@interface CardNumber : Serializable
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * __null_unspecified validation;
+ (CardNumber * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Device;
@class NSError;
@class IdentificationType;

SWIFT_CLASS("_TtC14MercadoPagoSDK9CardToken")
@interface CardToken : NSObject
@property (nonatomic, copy) NSString * __nullable cardNumber;
@property (nonatomic, copy) NSString * __nullable securityCode;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, strong) Cardholder * __nullable cardholder;
@property (nonatomic, strong) Device * __nullable device;
- (nonnull instancetype)initWithCardNumber:(NSString * __nullable)cardNumber expirationMonth:(NSInteger)expirationMonth expirationYear:(NSInteger)expirationYear securityCode:(NSString * __nullable)securityCode cardholderName:(NSString * __nonnull)cardholderName docType:(NSString * __nonnull)docType docNumber:(NSString * __nonnull)docNumber OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nullable)normalizeCardNumber:(NSString * __nullable)number;
- (BOOL)validate;
- (BOOL)validate:(BOOL)includeSecurityCode;
- (NSError * __nullable)validateCardNumber;
- (NSError * __nullable)validateCardNumber:(PaymentMethod * __nonnull)paymentMethod;
- (NSError * __nullable)validateSecurityCode;
- (NSError * __nullable)validateSecurityCode:(NSString * __nullable)securityCode;
- (NSError * __nullable)validateSecurityCodeWithPaymentMethod:(PaymentMethod * __nonnull)paymentMethod;
- (NSError * __nullable)validateSecurityCodeWithPaymentMethod:(NSString * __nonnull)securityCode paymentMethod:(PaymentMethod * __nonnull)paymentMethod bin:(NSString * __nonnull)bin;
- (NSError * __nullable)validateExpiryDate;
- (NSError * __nullable)validateExpiryDate:(NSInteger)month year:(NSInteger)year;
- (BOOL)validateExpMonth:(NSInteger)month;
- (BOOL)validateExpYear:(NSInteger)year;
- (NSError * __nullable)validateIdentification;
- (NSError * __nullable)validateIdentificationType;
- (NSError * __nullable)validateIdentificationNumber;
- (NSError * __nullable)validateIdentificationNumber:(IdentificationType * __nullable)identificationType;
- (NSError * __nullable)validateCardholderName;
- (BOOL)hasYearPassed:(NSInteger)year;
- (BOOL)hasMonthPassed:(NSInteger)year month:(NSInteger)month;
- (NSInteger)normalizeYear:(NSInteger)year;
- (BOOL)checkLuhn:(NSString * __nonnull)cardNumber;
- (NSString * __nullable)getBin;
- (NSString * __nonnull)toJSONString;
@end

@class Identification;

SWIFT_CLASS("_TtC14MercadoPagoSDK10Cardholder")
@interface Cardholder : NSObject
@property (nonatomic, copy) NSString * __nullable name;
@property (nonatomic, strong) Identification * __nullable identification;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Cardholder * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Cause")
@interface Cause : NSObject
@property (nonatomic, copy) NSString * __null_unspecified code;
@property (nonatomic, copy) NSString * __null_unspecified _description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Item;
@class Payer;
@class PreferencePaymentMethods;

SWIFT_CLASS("_TtC14MercadoPagoSDK18CheckoutPreference")
@interface CheckoutPreference : NSObject
@property (nonatomic, copy) NSString * __null_unspecified id;
@property (nonatomic, copy) NSArray<Item *> * __nullable items;
@property (nonatomic, strong) Payer * __nullable payer;
@property (nonatomic, strong) PreferencePaymentMethods * __nullable paymentMethods;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (CheckoutPreference * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (NSString * __nonnull)toJSONString;
- (double)getAmount;
- (NSInteger)getInstallments;
- (NSArray<PaymentMethod *> * __nullable)getExcludedPaymentMethods;
@end

@class NSCoder;

SWIFT_CLASS("_TtC14MercadoPagoSDK22CheckoutViewController")
@interface CheckoutViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK34CongratsPaymentMethodTableViewCell")
@interface CongratsPaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end

@class UITableView;
@class NSIndexPath;
@class Payment;

SWIFT_CLASS("_TtC14MercadoPagoSDK22CongratsViewController")
@interface CongratsViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITextFieldDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)declareAndInitCells;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (void)_setTitle:(Payment * __nonnull)payment;
- (void)_setIcon:(Payment * __nonnull)payment;
- (void)setDescription:(Payment * __nonnull)payment;
- (void)setAmount:(Payment * __nonnull)payment;
- (void)setPaymentId:(Payment * __nonnull)payment;
- (void)setPaymentMethodDescription:(Payment * __nonnull)payment;
- (void)setDateCreated:(Payment * __nonnull)payment;
- (void)setButtonText:(Payment * __nonnull)payment;
- (void)submitForm;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Currency")
@interface Currency : NSObject
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic, copy) NSString * __null_unspecified _description;
@property (nonatomic, copy) NSString * __null_unspecified symbol;
@property (nonatomic) NSInteger decimalPlaces;
@end

@class Phone;

SWIFT_CLASS("_TtC14MercadoPagoSDK8Customer")
@interface Customer : NSObject
@property (nonatomic, strong) Address * __nullable address;
@property (nonatomic, copy) NSArray<Card *> * __nullable cards;
@property (nonatomic, strong) NSNumber * __nullable defaultCard;
@property (nonatomic, copy) NSString * __nullable _description;
@property (nonatomic, strong) NSDate * __nullable dateCreated;
@property (nonatomic, strong) NSDate * __nullable dateLastUpdated;
@property (nonatomic, copy) NSString * __nullable email;
@property (nonatomic, copy) NSString * __nullable firstName;
@property (nonatomic, copy) NSString * __nullable _id;
@property (nonatomic, strong) Identification * __nullable identification;
@property (nonatomic, copy) NSString * __nullable lastName;
@property (nonatomic, strong) NSDictionary * __nullable metadata;
@property (nonatomic, strong) Phone * __nullable phone;
@property (nonatomic, strong) NSDate * __nullable registrationDate;
+ (Customer * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27CustomerCardsViewController")
@interface CustomerCardsViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nonnull instancetype)initWithCards:(NSArray<Card *> * __nullable)cards callback:(void (^ __nonnull)(Card * __nullable))callback OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)loadCards;
- (void)newCard;
@end

@class Fingerprint;

SWIFT_CLASS("_TtC14MercadoPagoSDK6Device")
@interface Device : NSObject
@property (nonatomic, strong) Fingerprint * __null_unspecified fingerprint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Discount")
@interface Discount : NSObject
@property (nonatomic, strong) NSNumber * __nonnull amountOff;
@property (nonatomic, strong) NSNumber * __nonnull couponAmount;
@property (nonatomic, copy) NSString * __null_unspecified currencyId;
@property (nonatomic) NSInteger _id;
@property (nonatomic, copy) NSString * __null_unspecified name;
@property (nonatomic, strong) NSNumber * __nonnull percentOff;
+ (Discount * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18ErrorTableViewCell")
@interface ErrorTableViewCell : UITableViewCell
@property (nonatomic) CGFloat height;
- (void)setError:(NSString * __nullable)error;
- (void)focus;
- (BOOL)hasError;
- (CGFloat)getHeight;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10FeesDetail")
@interface FeesDetail : NSObject
@property (nonatomic) double amount;
@property (nonatomic) double amountRefunded;
@property (nonatomic, copy) NSString * __null_unspecified feePayer;
@property (nonatomic, copy) NSString * __null_unspecified type;
+ (FeesDetail * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11Fingerprint")
@interface Fingerprint : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, id> * __nullable fingerprint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)toJSONString;
- (NSDictionary<NSString *, id> * __nonnull)deviceFingerprint;
- (NSArray * __nullable)devicesID;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18MercadoPagoService")
@interface MercadoPagoService : NSObject
- (void)request:(NSString * __nonnull)uri params:(NSString * __nullable)params body:(id __nullable)body method:(NSString * __nonnull)method success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end

@class SavedCardToken;

SWIFT_CLASS("_TtC14MercadoPagoSDK14GatewayService")
@interface GatewayService : MercadoPagoService
- (void)getToken:(NSString * __nonnull)url method:(NSString * __nonnull)method public_key:(NSString * __nonnull)public_key savedCardToken:(SavedCardToken * __nonnull)savedCardToken success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getToken:(NSString * __nonnull)url method:(NSString * __nonnull)method public_key:(NSString * __nonnull)public_key cardToken:(CardToken * __nonnull)cardToken success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16GenericErrorView")
@interface GenericErrorView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setErrorMessage:(NSString * __nonnull)errorMessage;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14Identification")
@interface Identification : NSObject
@property (nonatomic, copy) NSString * __nullable type;
@property (nonatomic, copy) NSString * __nullable number;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(NSString * __nullable)type number:(NSString * __nullable)number OBJC_DESIGNATED_INITIALIZER;
+ (Identification * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IdentificationService")
@interface IdentificationService : MercadoPagoService
- (void)getIdentificationTypes:(NSString * __nonnull)method uri:(NSString * __nonnull)uri public_key:(NSString * __nullable)public_key privateKey:(NSString * __nullable)privateKey success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18IdentificationType")
@interface IdentificationType : NSObject
@property (nonatomic, copy) NSString * __nullable _id;
@property (nonatomic, copy) NSString * __nullable name;
@property (nonatomic, copy) NSString * __nullable type;
@property (nonatomic) NSInteger minLength;
@property (nonatomic) NSInteger maxLength;
+ (IdentificationType * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayerCost;

SWIFT_CLASS("_TtC14MercadoPagoSDK11Installment")
@interface Installment : NSObject
@property (nonatomic, strong) Issuer * __null_unspecified issuer;
@property (nonatomic, copy) NSArray<PayerCost *> * __null_unspecified payerCosts;
@property (nonatomic, copy) NSString * __null_unspecified paymentMethodId;
@property (nonatomic, copy) NSString * __null_unspecified paymentTypeId;
+ (Installment * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24InstallmentTableViewCell")
@interface InstallmentTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost * __nonnull)payerCost amount:(double)amount;
@end

@class NSBundle;

SWIFT_CLASS("_TtC14MercadoPagoSDK26InstallmentsViewController")
@interface InstallmentsViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Issuer")
@interface Issuer : NSObject
@property (nonatomic, strong) NSNumber * __nullable _id;
@property (nonatomic, copy) NSString * __nullable name;
+ (Issuer * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19IssuerTableViewCell")
@interface IssuerTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithIssuer:(Issuer * __nonnull)issuer;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IssuersViewController")
@interface IssuersViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK4Item")
@interface Item : NSObject
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic) NSInteger quantity;
@property (nonatomic) double unitPrice;
@property (nonatomic, copy) NSString * __null_unspecified title;
@property (nonatomic, copy) NSString * __null_unspecified currencyId;
@property (nonatomic, copy) NSString * __null_unspecified categoryId;
- (nonnull instancetype)initWith_id:(NSString * __nonnull)_id quantity:(NSInteger)quantity unitPrice:(double)unitPrice OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)toJSONString;
+ (Item * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end

@class Setting;
@class UITextField;

SWIFT_CLASS("_TtC14MercadoPagoSDK25MPCardNumberTableViewCell")
@interface MPCardNumberTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified cardNumberTextField;
@property (nonatomic, strong) Setting * __null_unspecified setting;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * __null_unspecified)getCardNumber;
- (void)setIcon:(NSString * __nullable)pmId;
- (void)_setSetting:(Setting * __null_unspecified)setting;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> __nonnull)delegate;
- (BOOL)textField:(UITextField * __nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * __nonnull)string;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPCardholderNameTableViewCell")
@interface MPCardholderNameTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified cardholderNameTextField;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * __null_unspecified)getCardholderName;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> __nonnull)delegate;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPExpirationDateTableViewCell")
@interface MPExpirationDateTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified expirationDateTextField;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)getExpirationMonth;
- (NSInteger)getExpirationYear;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> __nonnull)delegate;
- (BOOL)textField:(UITextField * __nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * __nonnull)string;
@end

@class MerchantPayment;

SWIFT_CLASS("_TtC14MercadoPagoSDK13MPFlowBuilder")
@interface MPFlowBuilder : NSObject
+ (CheckoutViewController * __nonnull)starCheckoutViewController:(CheckoutPreference * __nonnull)preference callback:(void (^ __nonnull)(MerchantPayment * __nonnull))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPInstallmentsTableViewCell")
@interface MPInstallmentsTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost * __nullable)payerCost amount:(double)amount;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK33MPPaymentMethodEmptyTableViewCell")
@interface MPPaymentMethodEmptyTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28MPPaymentMethodTableViewCell")
@interface MPPaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithCard:(Card * __nullable)card;
- (void)fillWithCardTokenAndPaymentMethod:(CardToken * __nullable)card paymentMethod:(PaymentMethod * __nullable)paymentMethod;
- (void)fillWithPaymentMethod:(PaymentMethod * __nullable)paymentMethod;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPSecurityCodeTableViewCell")
@interface MPSecurityCodeTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified securityCodeTextField;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * __null_unspecified)getSecurityCode;
- (void)fillWithPaymentMethod:(PaymentMethod * __nonnull)pm;
@end

@class Token;

SWIFT_CLASS("_TtC14MercadoPagoSDK17MPServicesBuilder")
@interface MPServicesBuilder : NSObject
+ (void)createNewCardToken:(CardToken * __nonnull)cardToken success:(void (^ __nonnull)(Token * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (void)createToken:(SavedCardToken * __nonnull)savedCardToken success:(void (^ __nonnull)(Token * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (void)getPaymentMethods:(void (^ __nonnull)(NSArray<PaymentMethod *> * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (void)getIdentificationTypes:(void (^ __nonnull)(NSArray<IdentificationType *> * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (void)getIssuers:(PaymentMethod * __nonnull)paymentMethod success:(void (^ __nonnull)(NSArray<Issuer *> * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (void)createPayment:(NSString * __nonnull)merchantBaseUrl merchantPaymentUri:(NSString * __nonnull)merchantPaymentUri payment:(MerchantPayment * __nonnull)payment success:(void (^ __nonnull)(Payment * __nonnull))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NewCardViewController;
@class PromoViewController;

SWIFT_CLASS("_TtC14MercadoPagoSDK13MPStepBuilder")
@interface MPStepBuilder : NSObject
+ (CustomerCardsViewController * __nonnull)startCustomerCardsStep:(NSArray<Card *> * __nonnull)cards callback:(void (^ __nonnull)(Card * __nullable))callback;
+ (NewCardViewController * __nonnull)startNewCardStep:(PaymentMethod * __nonnull)paymentMethod requireSecurityCode:(BOOL)requireSecurityCode callback:(void (^ __nonnull)(CardToken * __nonnull))callback;
+ (IssuersViewController * __nonnull)startIssuersStep:(PaymentMethod * __nonnull)paymentMethod callback:(void (^ __nonnull)(Issuer * __nonnull))callback;
+ (InstallmentsViewController * __nonnull)startInstallmentsStep:(NSArray<PayerCost *> * __nonnull)payerCosts amount:(double)amount callback:(void (^ __nonnull)(PayerCost * __nullable))callback;
+ (CongratsViewController * __nonnull)startCongratsStep:(Payment * __nonnull)payment paymentMethod:(PaymentMethod * __nonnull)paymentMethod;
+ (PromoViewController * __nonnull)startPromosStep;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9MPToolbar")
@interface MPToolbar : UIToolbar
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC14MercadoPagoSDK21MPUserIdTableViewCell")
@interface MPUserIdTableViewCell : ErrorTableViewCell <UITextFieldDelegate, UIPickerViewDelegate, UIPickerViewDataSource>
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified userIdTypeTextField;
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified userIdValueTextField;
@property (nonatomic, strong) IBOutlet UIPickerView * __null_unspecified pickerIdentificationType;
@property (nonatomic, copy) NSArray<IdentificationType *> * __nonnull identificationTypes;
@property (nonatomic, strong) IdentificationType * __nullable identificationType;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * __nonnull)pickerView;
- (NSInteger)pickerView:(UIPickerView * __nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
- (NSString * __nullable)pickerView:(UIPickerView * __nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView * __nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (BOOL)textFieldShouldBeginEditing:(UITextField * __nonnull)textField;
- (BOOL)textField:(UITextField * __nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * __nonnull)string;
- (void)setFormWithIndex:(NSInteger)row;
- (void)awakeFromNib;
- (void)_setIdentificationTypes:(NSArray<IdentificationType *> * __nullable)identificationTypes;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * __null_unspecified)getUserIdType;
- (NSString * __null_unspecified)getUserIdValue;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> __nonnull)delegate;
@end

@class UIImage;
@class UINavigationController;
@class UIAlertView;

SWIFT_CLASS("_TtC14MercadoPagoSDK11MercadoPago")
@interface MercadoPago : NSObject <UIAlertViewDelegate>
+ (NSString * __nonnull)PUBLIC_KEY;
+ (NSString * __nonnull)PRIVATE_KEY;
+ (NSInteger)ERROR_KEY_CODE;
+ (NSInteger)ERROR_API_CODE;
+ (NSInteger)ERROR_UNKNOWN_CODE;
+ (NSInteger)ERROR_NOT_INSTALLMENTS_FOUND;
+ (NSInteger)ERROR_PAYMENT;
@property (nonatomic, copy) NSString * __nullable privateKey;
@property (nonatomic, copy) NSString * __nullable publicKey;
@property (nonatomic, copy) NSString * __nullable paymentMethodId;
@property (nonatomic, copy) NSString * __nullable paymentTypeId;
- (nonnull instancetype)initWithPublicKey:(NSString * __nonnull)publicKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithKeyType:(NSString * __nullable)keyType key:(NSString * __nullable)key OBJC_DESIGNATED_INITIALIZER;
- (void)createNewCardToken:(CardToken * __nonnull)cardToken success:(void (^ __nonnull)(Token * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)createToken:(SavedCardToken * __nonnull)savedCardToken success:(void (^ __nonnull)(Token * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getPaymentMethods:(void (^ __nonnull)(NSArray<PaymentMethod *> * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getIdentificationTypes:(void (^ __nonnull)(NSArray<IdentificationType *> * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getInstallments:(NSString * __nonnull)bin amount:(double)amount issuerId:(NSNumber * __nullable)issuerId paymentTypeId:(NSString * __nonnull)paymentTypeId success:(void (^ __nonnull)(NSArray<Installment *> * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getIssuers:(NSString * __nonnull)paymentMethodId success:(void (^ __nonnull)(NSArray<Issuer *> * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (BOOL)isCardPaymentType:(NSString * __nonnull)paymentTypeId;
+ (NSBundle * __nullable)getBundle;
+ (UIImage * __nullable)getImage:(NSString * __nonnull)name;
+ (CGRect)screenBoundsFixedToPortraitOrientation;
+ (void)showAlertViewWithError:(NSError * __nullable)error nav:(UINavigationController * __nullable)nav;
- (void)alertView:(UIAlertView * __nonnull)alertView clickedButtonAtIndex:(NSInteger)buttonIndex;
+ (void)createMPPayment:(MerchantPayment * __nonnull)payment success:(void (^ __nonnull)(Payment * __nonnull))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end



SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantPayment")
@interface MerchantPayment : NSObject
@property (nonatomic, strong) Issuer * __nullable issuer;
@property (nonatomic, copy) NSString * __null_unspecified cardTokenId;
@property (nonatomic) NSInteger campaignId;
@property (nonatomic) NSInteger installments;
@property (nonatomic, copy) NSArray<Item *> * __nonnull items;
@property (nonatomic, copy) NSString * __null_unspecified merchantAccessToken;
@property (nonatomic, strong) PaymentMethod * __null_unspecified paymentMethod;
- (nonnull instancetype)initWithItems:(NSArray<Item *> * __nonnull)items installments:(NSInteger)installments issuer:(Issuer * __nullable)issuer tokenId:(NSString * __nonnull)tokenId paymentMethod:(PaymentMethod * __nonnull)paymentMethod campaignId:(NSInteger)campaignId OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14MerchantServer")
@interface MerchantServer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (void)getCustomer:(NSString * __nonnull)merchantBaseUrl merchantGetCustomerUri:(NSString * __nonnull)merchantGetCustomerUri merchantAccessToken:(NSString * __nonnull)merchantAccessToken success:(void (^ __nonnull)(Customer * __nonnull))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (void)createPayment:(NSString * __nonnull)merchantBaseUrl merchantPaymentUri:(NSString * __nonnull)merchantPaymentUri payment:(MerchantPayment * __nonnull)payment success:(void (^ __nonnull)(Payment * __nonnull))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (void)createPreference:(CheckoutPreference * __nonnull)preference success:(void (^ __nonnull)(CheckoutPreference * __nonnull))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end

@class NSMutableData;

SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantService")
@interface MerchantService : MercadoPagoService
@property (nonatomic, strong) NSMutableData * __nonnull data;
- (void)getCustomer:(NSString * __nonnull)method merchant_access_token:(NSString * __nonnull)merchant_access_token success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)createPayment:(NSString * __nonnull)method payment:(MerchantPayment * __nonnull)payment success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)createPreference:(NSString * __nonnull)method preference:(CheckoutPreference * __nonnull)preference success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


@interface NSDictionary (SWIFT_EXTENSION(MercadoPagoSDK))
- (BOOL)isKeyValid:(NSString * __nonnull)dictKey;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21NewCardViewController")
@interface NewCardViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)getIndexForObject:(id __nonnull)object;
- (void)scrollToRow:(NSIndexPath * __nonnull)indexPath;
- (void)focusAndScrollForIndex:(NSInteger)index;
- (void)prev:(id __nullable)object;
- (void)next:(id __nullable)object;
- (void)done:(id __nullable)object;
- (void)prepareTableView;
- (void)submitForm;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * __nonnull)tableView;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)viewDidLayoutSubviews;
- (void)tableView:(UITableView * __nonnull)tableView willDisplayCell:(UITableViewCell * __nonnull)cell forRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)validateForm:(CardToken * __nonnull)cardToken;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Order")
@interface Order : NSObject
@property (nonatomic) NSInteger _id;
@property (nonatomic, copy) NSString * __null_unspecified type;
+ (Order * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Payer")
@interface Payer : NSObject
@property (nonatomic, copy) NSString * __null_unspecified email;
@property (nonatomic, strong) NSNumber * __nonnull _id;
@property (nonatomic, strong) Identification * __null_unspecified identification;
@property (nonatomic, copy) NSString * __null_unspecified type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Payer * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9PayerCost")
@interface PayerCost : NSObject
@property (nonatomic) NSInteger installments;
@property (nonatomic) double installmentRate;
@property (nonatomic, copy) NSArray<NSString *> * __null_unspecified labels;
@property (nonatomic) double minAllowedAmount;
@property (nonatomic) double maxAllowedAmount;
@property (nonatomic, copy) NSString * __null_unspecified recommendedMessage;
@property (nonatomic) double installmentAmount;
@property (nonatomic) double totalAmount;
- (nonnull instancetype)initWithInstallments:(NSInteger)installments installmentRate:(double)installmentRate labels:(NSArray<NSString *> * __nonnull)labels minAllowedAmount:(double)minAllowedAmount maxAllowedAmount:(double)maxAllowedAmount recommendedMessage:(NSString * __null_unspecified)recommendedMessage installmentAmount:(double)installmentAmount totalAmount:(double)totalAmount OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (PayerCost * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end

@class Refund;
@class TransactionDetails;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Payment")
@interface Payment : NSObject
@property (nonatomic, copy) NSString * __null_unspecified callForAuthorizeId;
@property (nonatomic, strong) Card * __null_unspecified card;
@property (nonatomic, copy) NSString * __null_unspecified currencyId;
@property (nonatomic, strong) NSDate * __null_unspecified dateApproved;
@property (nonatomic, strong) NSDate * __null_unspecified dateCreated;
@property (nonatomic, strong) NSDate * __null_unspecified dateLastUpdated;
@property (nonatomic, copy) NSString * __null_unspecified _description;
@property (nonatomic, copy) NSString * __null_unspecified externalReference;
@property (nonatomic, copy) NSArray<FeesDetail *> * __null_unspecified feesDetails;
@property (nonatomic) NSInteger _id;
@property (nonatomic) NSInteger installments;
@property (nonatomic, strong) NSObject * __null_unspecified metadata;
@property (nonatomic, strong) NSDate * __null_unspecified moneyReleaseDate;
@property (nonatomic, copy) NSString * __null_unspecified notificationUrl;
@property (nonatomic, strong) Order * __null_unspecified order;
@property (nonatomic, strong) Payer * __null_unspecified payer;
@property (nonatomic, copy) NSString * __null_unspecified paymentMethodId;
@property (nonatomic, copy) NSString * __null_unspecified paymentTypeId;
@property (nonatomic, copy) NSArray<Refund *> * __null_unspecified refunds;
@property (nonatomic, copy) NSString * __null_unspecified statementDescriptor;
@property (nonatomic, copy) NSString * __null_unspecified status;
@property (nonatomic, copy) NSString * __null_unspecified statusDetail;
@property (nonatomic) double transactionAmount;
@property (nonatomic) double transactionAmountRefunded;
@property (nonatomic, strong) TransactionDetails * __null_unspecified transactionDetails;
@property (nonatomic, copy) NSString * __null_unspecified collectorId;
@property (nonatomic) double couponAmount;
@property (nonatomic, strong) NSNumber * __nonnull differentialPricingId;
@property (nonatomic) NSInteger issuerId;
+ (Payment * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
+ (NSDate * __null_unspecified)getDateFromString:(NSString * __null_unspecified)string;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24PaymentDateTableViewCell")
@interface PaymentDateTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PaymentIDTableViewCell")
@interface PaymentIDTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PaymentMethod")
@interface PaymentMethod : Serializable
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic, copy) NSString * __null_unspecified name;
@property (nonatomic, copy) NSString * __null_unspecified paymentTypeId;
@property (nonatomic, copy) NSArray<Setting *> * __null_unspecified settings;
@property (nonatomic, copy) NSArray<NSString *> * __null_unspecified additionalInfoNeeded;
- (BOOL)isIssuerRequired;
- (BOOL)isSecurityCodeRequired:(NSString * __nonnull)bin;
- (BOOL)isAdditionalInfoNeeded:(NSString * __null_unspecified)param;
+ (PaymentMethod * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16PaymentMethodRow")
@interface PaymentMethodRow : NSObject
@property (nonatomic, copy) NSString * __nullable label;
@property (nonatomic, strong) Card * __nullable card;
@property (nonatomic, copy) NSString * __nullable icon;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19PaymentMethodSearch")
@interface PaymentMethodSearch : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (PaymentMethodSearch * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end

@class PaymentType;

SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentMethodSearchService")
@interface PaymentMethodSearchService : MercadoPagoService
@property (nonatomic, readonly, copy) NSString * __nonnull MP_SEARCH_BASE_URL;
@property (nonatomic, readonly, copy) NSString * __nonnull MP_SEARCH_PAYMENTS_URI;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)getPaymentMethods:(NSArray<PaymentType *> * __nullable)excludedPaymentTypes excludedPaymentMethods:(NSArray<PaymentMethod *> * __nullable)excludedPaymentMethods public_key:(NSString * __nonnull)public_key success:(void (^ __nonnull)(PaymentMethodSearch * __nonnull))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentMethodTableViewCell")
@interface PaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setLabel:(NSString * __nonnull)label;
- (void)setImageWithName:(NSString * __nonnull)imageName;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28PaymentMethodsViewController")
@interface PaymentMethodsViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14PaymentService")
@interface PaymentService : MercadoPagoService
- (void)getPaymentMethods:(NSString * __nonnull)method uri:(NSString * __nonnull)uri public_key:(NSString * __nonnull)public_key success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getInstallments:(NSString * __nonnull)method uri:(NSString * __nonnull)uri public_key:(NSString * __nonnull)public_key bin:(NSString * __nonnull)bin amount:(double)amount issuer_id:(NSNumber * __nullable)issuer_id payment_type_id:(NSString * __nonnull)payment_type_id success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getIssuers:(NSString * __nonnull)method uri:(NSString * __nonnull)uri public_key:(NSString * __nonnull)public_key payment_method_id:(NSString * __nonnull)payment_method_id success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK25PaymentTotalTableViewCell")
@interface PaymentTotalTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11PaymentType")
@interface PaymentType : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (PaymentType * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentVaultViewController")
@interface PaymentVaultViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)didReceiveMemoryWarning;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Phone")
@interface Phone : NSObject
@property (nonatomic, copy) NSString * __nullable areaCode;
@property (nonatomic, copy) NSString * __nullable number;
+ (Phone * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24PreferencePaymentMethods")
@interface PreferencePaymentMethods : NSObject
+ (PreferencePaymentMethods * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PromoEmptyTableViewCell")
@interface PromoEmptyTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;
@class UILabel;

SWIFT_CLASS("_TtC14MercadoPagoSDK18PromoTableViewCell")
@interface PromoTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified issuerImageView;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified sharesSubtitle;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified paymentMethodsSubtitle;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27PromoTyCDetailTableViewCell")
@interface PromoTyCDetailTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)setLabelWithIssuerName:(NSString * __nonnull)issuer legals:(NSString * __nonnull)legals;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19PromoViewController")
@interface PromoViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PromosService")
@interface PromosService : MercadoPagoService
- (void)getPromos:(NSString * __nonnull)url method:(NSString * __nonnull)method public_key:(NSString * __nonnull)public_key success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PromosTyCTableViewCell")
@interface PromosTyCTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PromosTyCViewController")
@interface PromosTyCViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Refund")
@interface Refund : NSObject
@property (nonatomic) double amount;
@property (nonatomic, strong) NSDate * __null_unspecified dateCreated;
@property (nonatomic) NSInteger _id;
@property (nonatomic, strong) NSObject * __null_unspecified metadata;
@property (nonatomic) NSInteger paymentId;
@property (nonatomic, copy) NSString * __null_unspecified source;
@property (nonatomic, copy) NSString * __null_unspecified uniqueSequenceNumber;
+ (Refund * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14SavedCardToken")
@interface SavedCardToken : NSObject
@property (nonatomic, copy) NSString * __nullable cardId;
@property (nonatomic, copy) NSString * __nullable securityCode;
@property (nonatomic, strong) Device * __nullable device;
@property (nonatomic) BOOL securityCodeRequired;
- (nonnull instancetype)initWithCardId:(NSString * __nonnull)cardId securityCode:(NSString * __nonnull)securityCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCard:(Card * __nonnull)card securityCode:(NSString * __nullable)securityCode securityCodeRequired:(BOOL)securityCodeRequired OBJC_DESIGNATED_INITIALIZER;
- (BOOL)validate;
- (BOOL)validateCardId;
- (BOOL)validateSecurityCode;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK12SecurityCode")
@interface SecurityCode : Serializable
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * __null_unspecified cardLocation;
@property (nonatomic, copy) NSString * __null_unspecified mode;
+ (SecurityCode * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@interface Serializable (SWIFT_EXTENSION(MercadoPagoSDK))
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK7Setting")
@interface Setting : Serializable
@property (nonatomic, strong) Bin * __null_unspecified bin;
@property (nonatomic, strong) CardNumber * __null_unspecified cardNumber;
@property (nonatomic, strong) SecurityCode * __null_unspecified securityCode;
+ (Setting * __nullable)getSettingByBin:(NSArray<Setting *> * __null_unspecified)settings bin:(NSString * __null_unspecified)bin;
+ (Setting * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Token")
@interface Token : NSObject
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic, copy) NSString * __null_unspecified publicKey;
@property (nonatomic, copy) NSString * __null_unspecified cardId;
@property (nonatomic, copy) NSString * __null_unspecified luhnValidation;
@property (nonatomic, copy) NSString * __null_unspecified status;
@property (nonatomic, copy) NSString * __null_unspecified usedDate;
@property (nonatomic) NSInteger cardNumberLength;
@property (nonatomic, strong) NSDate * __null_unspecified creationDate;
@property (nonatomic, copy) NSString * __null_unspecified truncCardNumber;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, strong) NSDate * __null_unspecified lastModifiedDate;
@property (nonatomic, strong) NSDate * __null_unspecified dueDate;
- (nonnull instancetype)initWith_id:(NSString * __nonnull)_id publicKey:(NSString * __nonnull)publicKey cardId:(NSString * __null_unspecified)cardId luhnValidation:(NSString * __null_unspecified)luhnValidation status:(NSString * __null_unspecified)status usedDate:(NSString * __null_unspecified)usedDate cardNumberLength:(NSInteger)cardNumberLength creationDate:(NSDate * __null_unspecified)creationDate truncCardNumber:(NSString * __null_unspecified)truncCardNumber securityCodeLength:(NSInteger)securityCodeLength expirationMonth:(NSInteger)expirationMonth expirationYear:(NSInteger)expirationYear lastModifiedDate:(NSDate * __null_unspecified)lastModifiedDate dueDate:(NSDate * __nullable)dueDate OBJC_DESIGNATED_INITIALIZER;
+ (Token * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18TransactionDetails")
@interface TransactionDetails : NSObject
@property (nonatomic) double couponAmount;
@property (nonatomic, copy) NSString * __null_unspecified externalResourceUrl;
@property (nonatomic, copy) NSString * __null_unspecified financialInstitution;
@property (nonatomic) double installmentAmount;
@property (nonatomic) double netReceivedAmount;
@property (nonatomic) double overpaidAmount;
@property (nonatomic) double totalPaidAmount;
+ (TransactionDetails * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(MercadoPagoSDK))
- (UIColor * __nonnull)UIColorFromRGB:(NSUInteger)rgbValue;
- (UIColor * __nonnull)errorCellColor;
- (UIColor * __nonnull)greenOkColor;
- (UIColor * __nonnull)redFailureColor;
- (UIColor * __nonnull)errorValidationTextColor;
- (UIColor * __nonnull)yellowFailureColor;
- (UIColor * __nonnull)blueMercadoPago;
- (UIColor * __nonnull)grayBaseText;
- (UIColor * __nonnull)grayDark;
- (UIColor * __nonnull)grayLight;
- (UIColor * __nonnull)grayLines;
- (UIColor * __nonnull)backgroundColor;
- (UIColor * __nonnull)white;
- (UIColor * __nonnull)installments;
@end


@interface UIDevice (SWIFT_EXTENSION(MercadoPagoSDK))
@end

@class NSString;
@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC14MercadoPagoSDK13UILoadingView")
@interface UILoadingView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)rect text:(NSString * __nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UILabel * __nonnull label;
@property (nonatomic, strong) UIActivityIndicatorView * __nonnull spinner;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19VaultViewController")
@interface VaultViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, copy) void (^ __nullable callback)(PaymentMethod * __nonnull, NSString * __nullable, Issuer * __nullable, NSInteger);
@property (nonatomic, strong) UILoadingView * __null_unspecified loadingView;
@property (nonatomic, strong) Card * __nullable selectedCard;
@property (nonatomic, strong) PayerCost * __nullable selectedPayerCost;
@property (nonatomic, strong) CardToken * __nullable selectedCardToken;
@property (nonatomic, strong) PaymentMethod * __nullable selectedPaymentMethod;
@property (nonatomic, strong) Issuer * __nullable selectedIssuer;
@property (nonatomic, copy) NSArray<Card *> * __nullable cards;
@property (nonatomic, copy) NSArray<PayerCost *> * __nullable payerCosts;
@property (nonatomic) BOOL securityCodeRequired;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic, copy) NSString * __nullable bin;
@property (nonatomic, copy) NSArray<PaymentMethod *> * __nullable excludedPaymentMethods;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)scrollToRow:(NSIndexPath * __nonnull)indexPath;
- (void)declareAndInitCells;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)showViewController:(UIViewController * __nonnull)vc;
- (void)loadPayerCosts;
- (void)submitForm;
@end

#pragma clang diagnostic pop
