# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MercadoPagoSDKExamplesObjectiveC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MercadoPagoSDKExamplesObjectiveC
    pod 'MercadoPagoPXTracking', '2.1.0'
    pod 'MercadoPagoServices', '1.0.6'

  target 'MercadoPagoSDKExamplesObjectiveCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
