# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MercadoPagoSDKExamplesObjectiveC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MercadoPagoSDKExamplesObjectiveC
    pod 'MercadoPagoPXTrackingV4', '2.1.3'
    pod 'MercadoPagoServicesV4', '1.0.18'
  # UI Meli Lib
    pod 'MLUI', '~> 5.0'

  target 'MercadoPagoSDKExamplesObjectiveCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
