# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodTester' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodTester
   pod 'MercadoPagoSDK', :path => '../'

  target 'PodTesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodTesterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
