# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MercadoPagoSDK' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'MercadoPagoTracker' 0.8.8
  # Pods for MercadoPagoSDK

  target 'MercadoPagoSDKTests' do
    inherit! :search_paths
    pod 'MercadoPagoTracker'
    # Pods for testing
  end

end
