# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MercadoPagoSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MercadoPagoSDK
  pod 'MercadoPagoPXTracking', '2.1.2'
  pod 'MercadoPagoServices', '1.0.9'
  
  # MELI UI
  pod 'MLUI', '4.0.0'

  target 'MercadoPagoSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
