# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MercadoPagoSDK' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
 use_frameworks!

# TODO TRACKER pod 'MercadoPagoTracker', '0.9.0'
  # Pods for MercadoPagoSDK



end
